# Generated by Django 4.2.13 on 2024-06-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internetshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='official_or_not_description',
            field=models.IntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=2048),
        ),
    ]
